import { FEATURED_PROJECTS } from "../../../pages/AboutMe/constants/FeaturedProjects";
import { TESTIMONIALS } from "../../../pages/AboutMe/constants/Testimonials";
import { Project } from "../../../models/Project";

export const PROJECTS: Project[] = [
  {
    featuredProject: FEATURED_PROJECTS[0],
    clientTestimonial: TESTIMONIALS[0],
    projectApproachSolution: "",
    projectChallenge: "",
    projectClientName: "",
    projectDescription: "",
    projectOverView: "",
    projectPeople: 0,
    projectIndustry: "",
    projectRequirements: [],
    projectResult: {
      customerSatisfaction: 0,
      efficiency: 0,
      overallCostPercentage: 0,
      salesGenerated: "",
      text: "",
    },
    projectSolutionImages: [],
    projectType: "We App",
    projectWebsiteUrl: "",
  },
  {
    featuredProject: FEATURED_PROJECTS[1],
    clientTestimonial: TESTIMONIALS[1],
    projectApproachSolution: "",
    projectChallenge: "",
    projectClientName: "",
    projectDescription: "",
    projectOverView: "",
    projectPeople: 0,
    projectIndustry: "",
    projectRequirements: [],
    projectResult: {
      customerSatisfaction: 0,
      efficiency: 0,
      overallCostPercentage: 0,
      salesGenerated: "",
      text: "",
    },
    projectSolutionImages: [],
    projectType: "Mobile App",
    projectWebsiteUrl: "",
  },
  {
    featuredProject: FEATURED_PROJECTS[2],
    clientTestimonial: TESTIMONIALS[1],
    projectApproachSolution: "",
    projectChallenge: "",
    projectClientName: "",
    projectDescription: "",
    projectOverView: "",
    projectPeople: 0,
    projectIndustry: "",
    projectRequirements: [],
    projectResult: {
      customerSatisfaction: 0,
      efficiency: 0,
      overallCostPercentage: 0,
      salesGenerated: "",
      text: "",
    },
    projectSolutionImages: [],
    projectType: "Frontend",
    projectWebsiteUrl: "",
  },
  {
    featuredProject: FEATURED_PROJECTS[3],
    clientTestimonial: TESTIMONIALS[3],
    projectApproachSolution: "",
    projectChallenge: "",
    projectClientName: "",
    projectDescription: "",
    projectOverView: "",
    projectPeople: 0,
    projectIndustry: "",
    projectRequirements: [],
    projectResult: {
      customerSatisfaction: 0,
      efficiency: 0,
      overallCostPercentage: 0,
      salesGenerated: "",
      text: "",
    },
    projectSolutionImages: [],
    projectType: "Backend",
    projectWebsiteUrl: "",
  },
];
